services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    ports:
      #      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - /etc/letsencrypt/:/etc/letsencrypt/
    restart: always

volumes:
  portainer_data:
    external: true
    name: portainer_data
